name: CI

on:
  push:
    branches:
      - feature/**
      - hotfix/**

  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build, run tests and package artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: dotnet build -c Release
      - name:
        run: dotnet test -c Release --no-build